### PR TITLE
feat: add flags for `account_id` and `access_config` for user inputs; add an english version of readme

### PR DESCRIPTION
**Pull request by NIZ-elsevier**
### Added
* A full english version of README. 
* Add a couple of flags to give user options to specify `account_id` and `access_config` name. 

### Changed
* Used version `1.2.0` in the `package.json` and `package-lock.json` files for this release.
* Modified test cases and error handling for the added flags

Note: The changes haven't been verified as I couldn't build the binary locally.

### CODE REVIEW

**Review by JacksonTian — APPROVED** [review]

**Comment by JacksonTian** [comment]
LGTM

**Comment by JacksonTian** [comment]
Cloud you sign the CLA?

**Comment by NIZ-elsevier** [comment]
Hi @JacksonTian, I think I have signed the CLA already, but let me try it again.

**Comment by NIZ-elsevier** [comment]
CLA sorted now.

**Pull request merged**
